DISTNAME       = Telodendria-v0.1.0
MASTER_SITES   = https://telodendria.io/pub/v0.1.0/
PKGNAME        = telodendria-0.1.0

CATEGORIES     = net
COMMENT        = Matrix homeserver implementation written in ANSI C
HOMEPAGE       = https://telodendria.io
MAINTAINER     = Jordan Bancino <jordan@bancino.net>

PERMIT_PACKAGE = Yes
MAKE_FILE      = contrib/Makefile

.include <bsd.port.mk>
